stages:
  - build
  - run

variables:
  image_version: "0.1.0"

build:
  stage: build
  image: docker:18.09
  only:
    refs:
      - /^master$/
  script:
    - docker build -t dp:$image_version .
    - docker tag dp:$image_version harbor.cloud-voyageone.cn/devops/dp:$image_version
    - docker login harbor.cloud-voyageone.cn -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push harbor.cloud-voyageone.cn/devops/dp:$image_version

run:
  stage: run
  tags:
    - "130"
    - shell
  only:
    refs:
      - /^master$/
  script:
    - docker pull harbor.cloud-voyageone.cn/devops/dp:$image_version
    - docker stop vo-dp
    - docker rm vo-dp
    - docker run -d --name vo-dp --network vo-dp -p 10.0.0.143:7654:7654 harbor.cloud-voyageone.cn/devops/dp:$image_version
    - docker update --restart unless-stopped